- alias: Morgenradio
  trigger:
    platform: template
    value_template: "{{ states.sensor.time.state == (states.input_datetime.morgenradio.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  condition:
    condition: template
    value_template: '{{ states.input_boolean.morgenradio.state == "on" }}'
  action:
    - service: media_player.sonos_join
      data:
        master: media_player.soverom
        entity_id:
          - media_player.bad
          - media_player.gang
          - media_player.kjkken
          - media_player.soverom
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.morgenradio
    - service: media_player.volume_set
      data:
        volume_level: '0.08'
      entity_id:
        - media_player.bad
        - media_player.gang
        - media_player.kjkken
        - media_player.soverom
        - media_player.stue
    - service: media_player.volume_set
      data:
        volume_level: '0.3'
      entity_id:
        - media_player.bad
    - service: media_player.select_source
      data:
        entity_id: media_player.soverom
        source: 'NRK P3'